[naverpost_ynk]
title = "네이버 포스트 ─ YNK엔터테인먼트"
url = "https://post.naver.com/my.naver?memberNo=33175148"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_keyeast]
title = "네이버 포스트 ─ 키이스트"
url = "https://post.naver.com/my.naver?memberNo=29770009"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_935]
title = "네이버 포스트 ─ 935엔터테인먼트"
url = "https://m.post.naver.com/my.naver?memberNo=36232354"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_msoop]
title = "네이버 포스트 ─ 매니지먼트숲"
url = "https://m.post.naver.com/my.nhn?memberNo=22903361"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_bh]
title = "네이버 포스트 ─ BH엔터테인먼트"
url = "https://post.naver.com/my.naver?memberNo=21724264"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_vast]
title = "네이버 포스트 ─ VAST엔터테인먼트"
url = "https://m.post.naver.com/my.naver?memberNo=32146648"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_culturedepot]
title = "네이버 포스트 ─ 문화창고"
url = "https://m.post.naver.com/my.nhn?memberNo=40792415"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"

[naverpost_hb]
title = "네이버 포스트 ─ HB엔터테인먼트"
url = "https://m.post.naver.com/my.naver?memberNo=3247896"
entrySelector = "ul.lst_feed li._cds.check_visible"
titleSelector = "strong.tit_feed.ell"
linkSelector = "div.text_area a.link_end"
imageSelector = "div.image_area a img"
contentSelector = "p.text_feed.ell"
waitUntil = "networkidle"